const works = [

  {
    title: "The Portal: Realms of Mountains and Seas",
    year: "2025",
    category: "Immersive Installation",
    categoryKey: "installation",
    image: "images/work-portal.jpg",
    url: "works/the-portal.html",
    featured: true,
    curatorialSection: "environment",
    curatorialOrder: 1,
    tags: "Geology • Landscape • Deep Time",
  },

  {
    title: "Listening Landscape",
    year: "2023",
    category: "Sound • Environment • Generative System",
    categoryKey: "sound",
    image: "images/work-listening-landscape.jpg",
    url: "works/listening-landscape.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 10,
    tags: "Soundscape • Environmental Data • Generative",
  },

  {
    title: "The Stream of Consciousness Photobooth",
    year: "2025",
    category: "Interactive Generative Installation",
    categoryKey: "interactive",
    image: "images/work-the-stream-of-consciousness-photobooth.jpg",
    url: "works/the-stream-of-consciousness-photobooth.html",
    featured: true,
    curatorialSection: "system",
    curatorialOrder: 1,
    tags: "AI Language • Identity • Participatory System",
  },

  {
    title: "Red",
    year: "2025",
    category: "Real-time Generative Audiovisual Installation",
    categoryKey: "installation",
    image: "images/work-red.jpg",
    url: "works/red.html",
    featured: true,
    curatorialSection: "system",
    curatorialOrder: 3,
    tags: "Environmental Data • Multi-channel • Signal",
  },

  {
    title: "Hide and See",
    year: "2024",
    category: "Interactive Sound Installation",
    categoryKey: "interactive",
    image: "images/work-hide-and-see.jpg",
    url: "works/hide-and-see.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 3,
    tags: "Play • Listening • Spatial Interaction",
  },

  {
    title: "Cultivated Reality",
    year: "2021–2022",
    category: "VR Video • Digital Prints",
    categoryKey: "digital",
    image: "images/work-cultivated.jpg",
    url: "works/cultivated-reality.html",
    featured: false,
    curatorialSection: "system",
    curatorialOrder: 2,
    tags: "Media Critique • Image Systems • VR",
  },

  {
    title: "Cobweb",
    year: "2024",
    category: "Sound Installation",
    categoryKey: "sound",
    image: "images/work-cobweb.jpg",
    url: "works/cobweb.html",
    featured: true,
    curatorialSection: "environment",
    curatorialOrder: 20,
    tags: "",
  },

  {
    title: "A Story Floating on the Sea",
    year: "2025",
    category: "Participatory Sound Art Installation",
    categoryKey: "installation",
    image: "images/work-a-story-floating-on-the-sea.jpg",
    url: "works/a-story-floating-on-the-sea.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 11,
    tags: "",
  },

  {
    title: "Dreams, Wishes, Rivers",
    year: "2025",
    category: "AI Audiovisual Installation",
    categoryKey: "installation",
    image: "images/work-dreams-wishes-rivers.jpg",
    url: "works/dreams-wishes-rivers.html",
    featured: true,
    curatorialSection: "environment",
    curatorialOrder: 12,
    tags: "",
  },

  {
    title: "Colored Lab",
    year: "2024",
    category: "Interactive Installation",
    categoryKey: "installation",
    image: "images/work-colored-lab.jpg",
    url: "works/colored-lab.html",
    featured: false,
    curatorialSection: "system",
    curatorialOrder: 11,
    tags: "",
  },

  {
    title: "Records of Landscape",
    year: "2023",
    category: "Interactive Sound Installation",
    categoryKey: "installation",
    image: "images/work-records-of-landscape.jpg",
    url: "works/records-of-landscape.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 13,
    tags: "",
  },

  {
    title: "The Birds that Leave the Nest",
    year: "2023",
    category: "Interactive Sound Installation",
    categoryKey: "installation",
    image: "images/work-the-birds-that-leave-the-nest.jpg",
    url: "works/the-birds-that-leave-the-nest.html",
    featured: true,
    curatorialSection: "sonic",
    curatorialOrder: 2,
    tags: "",
  },

  {
    title: "Memory Fruit",
    year: "2023",
    category: "Interactive Sound Installation",
    categoryKey: "installation",
    image: "images/work-memory-fruit.jpg",
    url: "works/memory-fruit.html",
    featured: true,
    curatorialSection: "sonic",
    curatorialOrder: 3,
    tags: "",
  },

  {
    title: "Listening Landscape, Seaside and City of Kaohsiung",
    year: "2023",
    category: "Four-channel Video Installation",
    categoryKey: "installation",
    image: "images/work-listening-landscape-seaside-and-city-of-kaohsiung.jpg",
    url: "works/listening-landscape-seaside-and-city-of-kaohsiung.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 4,
    tags: "",
  },

  {
    title: "River Concert",
    year: "2022",
    category: "Art Project",
    categoryKey: "digital",
    image: "images/work-river-concert.jpg",
    url: "works/river-concert.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 5,
    tags: "",
  },

  {
    title: "I Remember in the Moonlight",
    year: "2024",
    category: "Interactive Sound Installation",
    categoryKey: "installation",
    image: "images/work-i-remember-in-the-moonlight.jpg",
    url: "works/i-remember-in-the-moonlight.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 14,
    tags: "",
  },

  {
    title: "Flowing Crowd with Musical Notes",
    year: "2022",
    category: "Interactive Intelligent Image Music System",
    categoryKey: "digital",
    image: "images/work-flowing-crowd-with-musical-notes.jpg",
    url: "works/flowing-crowd-with-musical-notes.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 15,
    tags: "",
  },

  {
    title: "Surrounding Spectrum — Yanshui Township",
    year: "2021",
    category: "Field Investigation & Digital Output",
    categoryKey: "digital",
    image: "images/work-surrounding-spectrum-yanshui.jpg",
    url: "works/surrounding-spectrum-yanshui.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 16,
    tags: "",
  },

  {
    title: "Architecture 1/N",
    year: "2021",
    category: "10-channel Video Sound Installation",
    categoryKey: "installation",
    image: "images/work-architecture-1-n.jpg",
    url: "works/architecture-1-n.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 16,
    tags: "",
  },

  {
    title: "Facial Sound Mask",
    year: "2021",
    category: "Field Research & Installation",
    categoryKey: "installation",
    image: "images/work-facial-sound-mask.jpg",
    url: "works/facial-sound-mask.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 17,
    tags: "",
  },

  {
    title: "Hourglass",
    year: "2020",
    category: "Interactive Video Sound Installation",
    categoryKey: "installation",
    image: "images/work-hourglass.jpg",
    url: "works/hourglass.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 17,
    tags: "",
  },

  {
    title: "Surrounding Spectrum — Lequn Village, Huayin Street, Xiluo Township",
    year: "2019",
    category: "Field Survey & Digital Output",
    categoryKey: "digital",
    image: "images/work-surrounding-spectrum-lequn.jpg",
    url: "works/surrounding-spectrum-lequn.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 18,
    tags: "",
  },

  {
    title: "Rainbow Stage",
    year: "2020",
    category: "Interactive Audiovisual Installation",
    categoryKey: "installation",
    image: "images/work-rainbow-stage.jpg",
    url: "works/rainbow-stage.html",
    featured: true,
    curatorialSection: "system",
    curatorialOrder: 4,
    tags: "",
  },

  {
    title: "An Infinite Shrinking Crisis",
    year: "2019",
    category: "Video Installation",
    categoryKey: "installation",
    image: "images/work-an-infinite-shrinking-crisis.jpg",
    url: "works/an-infinite-shrinking-crisis.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 19,
    tags: "",
  },

  {
    title: "Ephemera No.1, No.2, and No.3",
    year: "2018",
    category: "Real-time Audiovisual Installation",
    categoryKey: "installation",
    image: "images/work-ephemera-1-2-3.jpg",
    url: "works/ephemera-1-2-3.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 20,
    tags: "",
  },

  {
    title: "Emergency Dialogue of Plants",
    year: "2018",
    category: "Sound Installation",
    categoryKey: "installation",
    image: "images/work-emergency-dialogue-of-plants.jpg",
    url: "works/emergency-dialogue-of-plants.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 19,
    tags: "",
  },

  {
    title: "A Stage for Everyone",
    year: "2016",
    category: "Interactive Audiovisual Installation",
    categoryKey: "installation",
    image: "images/work-a-stage-for-everyone.jpg",
    url: "works/a-stage-for-everyone.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 21,
    tags: "",
  },

  {
    title: "The Childhood Series",
    year: "2013",
    category: "Site-specific Sound Installation",
    categoryKey: "sound",
    image: "images/work-the-childhood-series.jpg",
    url: "works/the-childhood-series.html",
    featured: false,
    curatorialSection: "system",
    curatorialOrder: 30,
    tags: "",
  },

  {
    title: "The English Word “Asia”",
    year: "2015",
    category: "Video • Sound",
    categoryKey: "video",
    image: "images/work-the-english-word-asia.jpg",
    url: "works/the-english-word-asia.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 31,
    tags: "",
  },

  {
    title: "Sea Inside",
    year: "2014",
    category: "Audio-Visual Installation",
    categoryKey: "installation",
    image: "images/work-sea-inside.jpg",
    url: "works/sea-inside.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 32,
    tags: "",
  },

  {
    title: "Screen Test",
    year: "2025",
    category: "Social Media Art Project",
    categoryKey: "digital",
    image: "images/work-screen-test.jpg",
    url: "works/screen-test.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 33,
    tags: "",
  },

  {
    title: "Dongju Telephone",
    year: "2015",
    category: "Interactive Media Installation",
    categoryKey: "digital",
    image: "images/work-dongju-telephone.jpg",
    url: "works/dongju-telephone.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 34,
    tags: "",
  },

  {
    title: "Frequency Protocol Series",
    year: "2016",
    category: "Digital Printing • Lamp",
    categoryKey: "installation",
    image: "images/work-frequency-protocol-series.jpg",
    url: "works/frequency-protocol-series.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 22,
    tags: "Telephone Buttons • Sound Image",
  },

  {
    title: "Young in the Bottle",
    year: "2017",
    category: "Sound Installation",
    categoryKey: "sound",
    image: "images/work-young-in-the-bottle.jpg",
    url: "works/young-in-the-bottle.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 23,
    tags: "Questions • Voice Archive • Glass Bottle",
  },

  {
    title: "Invisible Score Series",
    year: "2017",
    category: "Photograph • Sound Installation",
    categoryKey: "sound",
    image: "images/work-invisible-score-series.jpg",
    url: "works/invisible-score-series.html",
    featured: false,
    curatorialSection: "environment",
    curatorialOrder: 24,
    tags: "Landscape Listening • Score",
  },

  {
    title: "Ecology Notes",
    year: "2017",
    category: "One Channel Video",
    categoryKey: "video",
    image: "images/work-ecology-notes.jpg",
    url: "works/ecology-notes.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 25,
    tags: "Field Research • Ecological Reading",
  },

  {
    title: "Welcome South Series",
    year: "2017",
    category: "Photograph • Digital Print on Canvas",
    categoryKey: "digital",
    image: "images/work-welcome-south-series.jpg",
    url: "works/welcome-south-series.html",
    featured: false,
    curatorialSection: "system",
    curatorialOrder: 26,
    tags: "RGB • Expansion Scene • Urban Illusion",
  },

  {
    title: "Keep Distance - (Body Synthesizer)",
    year: "2018",
    category: "Interactive Sound Installation",
    categoryKey: "installation",
    image: "images/work-keep-distance-body-synthesizer.jpg",
    url: "works/keep-distance-body-synthesizer.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 27,
    tags: "Distance • Body • Anxiety",
  },


  {
    title: "Urban Sound-Sketching",
    year: "2023–present",
    category: "Environmental Sound Data / Algorithmic Imagery / AR Project",
    categoryKey: "digital",
    image: "images/work-urban-sound-sketching.jpg",
    url: "works/urban-sound-sketching.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 35,
    tags: "Fieldwork • Listening • Urban Memory",
  },

  {
    title: "The Flood Submerged This City",
    year: "2025",
    category: "Net Art / Web Installation",
    categoryKey: "digital",
    image: "images/work-the-flood-submerged-this-city.jpg",
    url: "works/the-flood-submerged-this-city.html",
    featured: false,
    curatorialSection: "system",
    curatorialOrder: 36,
    tags: "Web Interface • Big Data • Generative Flood",
  },

  {
    title: "Digital Wasteland",
    year: "2025",
    category: "Interactive Generative Installation",
    categoryKey: "digital",
    image: "images/work-digital-wasteland.jpg",
    url: "works/digital-wasteland.html",
    featured: true,
    curatorialSection: "sonic",
    curatorialOrder: 1,
    tags: "Active Forgetting • Bytebeat • Data Excess",
  },

  {
    title: "Infinity Evolving World",
    year: "2025",
    category: "AI-driven Video Artwork",
    categoryKey: "video",
    image: "images/work-infinity-evolving-world.jpg",
    url: "works/infinity-evolving-world.html",
    featured: false,
    curatorialSection: "system",
    curatorialOrder: 38,
    tags: "AI • Urban Anxiety • Ecological Precarity",
  },

  {
    title: "Listen to the Breath of the City",
    year: "2026",
    category: "Sound Art / Networked Interactive System",
    categoryKey: "sound",
    image: "images/work-listen-to-the-breath-of-the-city.jpg",
    url: "works/listen-to-the-breath-of-the-city.html",
    featured: false,
    curatorialSection: "sonic",
    curatorialOrder: 39,
    tags: "Urban Rhythm • Breathing Patterns • Participation",
  },

  {
    title: "Wishing Well",
    year: "2026",
    category: "Interactive Digital Installation",
    categoryKey: "digital",
    image: "images/work-wishing-well.jpg",
    url: "works/wishing-well.html",
    featured: true,
    curatorialSection: "system",
    curatorialOrder: 1,
    tags: "Consumer Critique • Algorithm • Digital Alienation",
  },

];
